### ISSUE TITLE
Civil war broke 

### ISSUE THREAD

**Issue by Hunterchase** [ZerdNerd/crossoverworldmod#1]
[error.log](https://github.com/ZerdNerd/crossoverworldmod/files/6368682/error.log)

**Comment by ZerdNerd** [comment]
GAME.log, NOT error.log.

**Comment by Hunterchase** [comment]
[game.log](https://github.com/ZerdNerd/crossoverworldmod/files/6368693/game.log)

**Comment by Hunterchase** [comment]
does that work

**Comment by ZerdNerd** [comment]
Send me a save from peace conference dated BEFORE 18 April 1942.

**Comment by Hunterchase** [comment]
why

**Comment by Hunterchase** [comment]
[Desktop.zip](https://github.com/ZerdNerd/crossoverworldmod/files/6368760/Desktop.zip)

**Comment by ZerdNerd** [comment]
Issue reproduced successfully.

**Comment by ZerdNerd** [comment]
Fixed in dev build. Will release soon.
