### ISSUE TITLE
Greenland Event Crash

### ISSUE THREAD

**Issue by Eugene3129** [ZerdNerd/crossoverworldmod#2]
The game crashes whenever I click the option to recruit Kayo the Chameleon as Greenland after he defects to me (event greenland.59.a). This happened when I hadn't created an agency, when I had created an agency but I didn't have a free operative slot and when I had an available operative slot. The error happened yesterday and earlier today when I tried to recruit him.
[error.log](https://github.com/ZerdNerd/crossoverworldmod/files/8241647/error.log)
[system.log](https://github.com/ZerdNerd/crossoverworldmod/files/8241657/system.log)
[game.log](https://github.com/ZerdNerd/crossoverworldmod/files/8241667/game.log)

**Comment by ZerdNerd** [comment]
Will look into this, never happened during testing but we'll see what's going on.

**Comment by Eugene3129** [comment]
Ok. Thank you!

**Comment by ZerdNerd** [comment]
Traced to events in which Kayo and Vultur defect to Greenland and Iceworld respectively. Both temporaily turned off in bd79ed34b1e34893c8fc89d3c71fb5381b412252
